using System.Text.Json.Serialization;

namespace Easydict.TranslationService.Models;

/// <summary>
/// What a <see cref="TextAction"/> does when the user triggers it.
/// </summary>
[JsonConverter(typeof(JsonStringEnumConverter))]
public enum TextActionType
{
    /// <summary>Open <see cref="TextAction.UrlTemplate"/> in the default browser with the text substituted in.</summary>
    OpenUrl,

    /// <summary>Run one specific translation service (built-in or plugin) on the text and show its result.</summary>
    RunService
}

/// <summary>
/// A declarative, user-configurable action that operates on selected or entered text.
/// Actions surface on the selection pop-up strip and in each window's Actions menu.
/// This is Easydict's own action interface; third-party plugin runtimes contribute
/// <see cref="TextActionType.RunService"/> actions that target their service id.
/// </summary>
public sealed record TextAction
{
    /// <summary>Stable identifier. Built-ins use a short slug ("google"); service actions use "service:&lt;serviceId&gt;".</summary>
    public required string Id { get; init; }

    /// <summary>Title shown on buttons and menu items.</summary>
    public required string Title { get; init; }

    /// <summary>What the action does.</summary>
    public required TextActionType Type { get; init; }

    /// <summary>
    /// URL template for <see cref="TextActionType.OpenUrl"/>. Supported placeholders:
    /// <c>{encodedText}</c>, <c>{encodedTranslation}</c>, <c>{from}</c>, <c>{to}</c>.
    /// </summary>
    public string? UrlTemplate { get; init; }

    /// <summary>Target service id for <see cref="TextActionType.RunService"/>.</summary>
    public string? ServiceId { get; init; }

    /// <summary>Optional Segoe MDL2 glyph for <see cref="TextActionType.OpenUrl"/> actions.</summary>
    public string? IconGlyph { get; init; }

    /// <summary>Whether the action is offered at all (Actions menu).</summary>
    public bool IsEnabled { get; init; } = true;

    /// <summary>Whether the action also appears as a button on the selection pop-up strip.</summary>
    public bool ShowOnPopButton { get; init; }

    /// <summary>True for actions shipped with Easydict (they can be edited but are restored by "reset").</summary>
    public bool IsBuiltIn { get; init; }

    /// <summary>
    /// Origin marker for actions generated by a subsystem (for example "bob" for actions created
    /// when a Bob plugin is installed) so they can be removed together with their source.
    /// </summary>
    public string? Source { get; init; }
}
