using Easydict.TranslationService.Models;

namespace Easydict.TranslationService.TextActions;

/// <summary>
/// Validation and factory helpers for <see cref="TextAction"/>.
/// </summary>
public static class TextActionValidator
{
    /// <summary>Prefix of ids generated by <see cref="ForService"/>.</summary>
    public const string ServiceActionIdPrefix = "service:";

    /// <summary>Returns <c>null</c> when the action is well-formed, otherwise a short reason.</summary>
    public static string? Validate(TextAction? action)
    {
        if (action is null)
        {
            return "Action is null.";
        }

        if (string.IsNullOrWhiteSpace(action.Id))
        {
            return "Action id is empty.";
        }

        if (string.IsNullOrWhiteSpace(action.Title))
        {
            return "Action title is empty.";
        }

        return action.Type switch
        {
            TextActionType.OpenUrl => TextActionUrlBuilder.ValidateTemplate(action.UrlTemplate),
            TextActionType.RunService => string.IsNullOrWhiteSpace(action.ServiceId) ? "Service id is empty." : null,
            _ => "Unknown action type."
        };
    }

    /// <summary>Create the canonical "run this service" action for a service id.</summary>
    public static TextAction ForService(string serviceId, string title, bool showOnPopButton = true, string? source = null)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(serviceId);

        return new TextAction
        {
            Id = ServiceActionIdPrefix + serviceId,
            Title = string.IsNullOrWhiteSpace(title) ? serviceId : title,
            Type = TextActionType.RunService,
            ServiceId = serviceId,
            ShowOnPopButton = showOnPopButton,
            Source = source
        };
    }

    /// <summary>The service id targeted by a service action id, or <c>null</c> for other ids.</summary>
    public static string? ServiceIdFromActionId(string? actionId)
    {
        return actionId is not null && actionId.StartsWith(ServiceActionIdPrefix, StringComparison.Ordinal)
            ? actionId.Substring(ServiceActionIdPrefix.Length)
            : null;
    }
}
