//! Generates allocation-free, typed C# accessors for compiled named slots and actions.

use std::fmt::{self, Write};

use dxaml_ir::{IrBindingMode, IrDocument};

const INDENT: &str = "    ";

fn write_line(output: &mut String, depth: usize, content: impl fmt::Display) {
    for _ in 0..depth {
        output.push_str(INDENT);
    }

    writeln!(output, "{content}").unwrap();
}

macro_rules! emit_line {
    ($output:expr, $depth:expr) => {
        write_line($output, $depth, "")
    };
    ($output:expr, $depth:expr, $($arg:tt)*) => {
        write_line($output, $depth, format_args!($($arg)*))
    };
}

/// Generates the C# glue for one compiled view.
pub fn generate(document: &IrDocument) -> Result<String, String> {
    let (namespace, view_name) = document
        .class_name
        .rsplit_once('.')
        .ok_or_else(|| "x:Class must contain a namespace and type name".to_string())?;
    if !namespace.split('.').all(is_identifier) || !is_identifier(view_name) {
        return Err(format!(
            "'{}' is not a supported C# type name",
            document.class_name
        ));
    }

    let bindings_name = format!("{view_name}DirectBindings");
    let mut output = String::with_capacity(4096);
    emit_line!(&mut output, 0, "// <auto-generated />");
    emit_line!(&mut output, 0, "#nullable enable");
    emit_line!(&mut output, 0, "using System;");
    emit_line!(&mut output, 0, "using Easydict.DirectXaml;");
    emit_line!(&mut output, 0);
    emit_line!(&mut output, 0, "namespace {namespace};");
    emit_line!(&mut output, 0);
    emit_line!(&mut output, 0, "internal sealed class {bindings_name}");
    emit_line!(&mut output, 0, "{{");
    emit_line!(&mut output, 1, "private readonly CompiledView _view;");
    emit_line!(&mut output, 0);
    emit_line!(
        &mut output,
        1,
        "internal {bindings_name}(CompiledView view)"
    );
    emit_line!(&mut output, 1, "{{");
    emit_line!(&mut output, 2, "ArgumentNullException.ThrowIfNull(view);");
    emit_line!(&mut output, 2, "_view = view;");
    emit_line!(&mut output, 1, "}}");

    if !document.bindings.is_empty() {
        generate_x_bindings(document, &mut output)?;
    }

    for slot in &document.named_slots {
        if !is_identifier(&slot.name) {
            return Err(format!("slot '{}' is not a C# identifier", slot.name));
        }
        emit_line!(&mut output, 0);
        emit_line!(
            &mut output,
            1,
            "internal const int {}Node = {};",
            slot.name,
            slot.node
        );
        for property in &slot.mutable {
            let (parameter_type, runtime_setter) = setter(&property.property).ok_or_else(|| {
                format!(
                    "slot '{}.{}' has no C# runtime setter",
                    slot.name, property.property
                )
            })?;
            emit_line!(
                &mut output,
                1,
                "internal void Set{}{}({parameter_type} value) => _view.{runtime_setter}(\"{}\", value);",
                slot.name,
                property.property,
                escape_csharp_string(&slot.name)
            );
        }
    }

    for action in &document.actions {
        emit_line!(&mut output, 0);
        emit_line!(
            &mut output,
            1,
            "internal const string Action{}{} = \"{}\";",
            action.node,
            pascal_case(&action.event),
            escape_csharp_string(&action.handler)
        );
    }

    emit_line!(&mut output, 0, "}}");
    Ok(output)
}

fn generate_x_bindings(document: &IrDocument, output: &mut String) -> Result<(), String> {
    let context_type = document
        .binding_context_type
        .as_deref()
        .ok_or_else(|| "bindings require binding_context_type".to_string())?;
    if !is_qualified_identifier(context_type) {
        return Err(format!(
            "binding_context_type '{context_type}' is not a supported C# type name"
        ));
    }
    let context_type = format!("global::{context_type}");

    for binding in &document.bindings {
        if binding.source_path.len() != 1 || !is_identifier(&binding.source_path[0]) {
            return Err(format!(
                "binding target '{}.{}' needs one simple source property path",
                binding.target_node, binding.target_property
            ));
        }
        if bound_setter(&binding.target_property).is_none() {
            return Err(format!(
                "binding target '{}.{}' has no C# runtime setter",
                binding.target_node, binding.target_property
            ));
        }
    }

    let has_one_way = document
        .bindings
        .iter()
        .any(|binding| binding.mode == IrBindingMode::OneWay);

    emit_line!(output, 0);
    emit_line!(
        output,
        1,
        "private {context_type} _bindingContext = default!;"
    );
    emit_line!(output, 1, "private bool _hasBindingContext;");
    emit_line!(output, 0);
    emit_line!(
        output,
        1,
        "internal void SetBindingContext({context_type} value) =>"
    );
    emit_line!(
        output,
        2,
        "_view.Dispatch(() => SetBindingContextCore(value));"
    );
    emit_line!(output, 0);
    emit_line!(
        output,
        1,
        "private void SetBindingContextCore({context_type} value)"
    );
    emit_line!(output, 1, "{{");
    if has_one_way {
        emit_line!(
            output,
            2,
            "if (_hasBindingContext && _bindingContext is global::System.ComponentModel.INotifyPropertyChanged oldContext)"
        );
        emit_line!(
            output,
            3,
            "oldContext.PropertyChanged -= OnBindingContextPropertyChanged;"
        );
    }
    emit_line!(output, 2, "_bindingContext = value;");
    emit_line!(output, 2, "_hasBindingContext = true;");
    if has_one_way {
        emit_line!(
            output,
            2,
            "if (_bindingContext is global::System.ComponentModel.INotifyPropertyChanged newContext)"
        );
        emit_line!(
            output,
            3,
            "newContext.PropertyChanged += OnBindingContextPropertyChanged;"
        );
    }
    emit_line!(output, 2, "ApplyBindings();");
    emit_line!(output, 1, "}}");
    emit_line!(output, 0);
    emit_line!(output, 1, "internal void ClearBindingContext() =>");
    emit_line!(output, 2, "_view.Dispatch(ClearBindingContextCore);");
    emit_line!(output, 0);
    emit_line!(output, 1, "private void ClearBindingContextCore()");
    emit_line!(output, 1, "{{");
    if has_one_way {
        emit_line!(
            output,
            2,
            "if (_hasBindingContext && _bindingContext is global::System.ComponentModel.INotifyPropertyChanged oldContext)"
        );
        emit_line!(
            output,
            3,
            "oldContext.PropertyChanged -= OnBindingContextPropertyChanged;"
        );
    }
    emit_line!(output, 2, "_bindingContext = default!;");
    emit_line!(output, 2, "_hasBindingContext = false;");
    emit_line!(output, 1, "}}");
    emit_line!(output, 0);
    emit_line!(output, 1, "private void ApplyBindings()");
    emit_line!(output, 1, "{{");
    emit_line!(output, 2, "if (!_hasBindingContext) return;");
    for binding in &document.bindings {
        write_bound_setter(
            output,
            binding.target_node,
            &binding.target_property,
            &binding.source_path[0],
        )?;
    }
    emit_line!(output, 1, "}}");

    if has_one_way {
        let mut one_way_sources = Vec::new();
        for binding in &document.bindings {
            if binding.mode == IrBindingMode::OneWay
                && !one_way_sources.contains(&binding.source_path[0].as_str())
            {
                one_way_sources.push(binding.source_path[0].as_str());
            }
        }
        emit_line!(output, 0);
        emit_line!(
            output,
            1,
            "private void OnBindingContextPropertyChanged(object? sender, global::System.ComponentModel.PropertyChangedEventArgs e)"
        );
        emit_line!(output, 1, "{{");
        emit_line!(output, 2, "string? changedProperty = e.PropertyName;");
        emit_line!(output, 2, "if (!string.IsNullOrEmpty(changedProperty))");
        emit_line!(output, 2, "{{");
        emit_line!(output, 3, "switch (changedProperty)");
        emit_line!(output, 3, "{{");
        for source in one_way_sources {
            emit_line!(output, 4, "case nameof({context_type}.{source}):");
            emit_line!(output, 5, "break;");
        }
        emit_line!(output, 4, "default:");
        emit_line!(output, 5, "return;");
        emit_line!(output, 3, "}}");
        emit_line!(output, 2, "}}");
        emit_line!(
            output,
            2,
            "_ = _view.TryDispatch(() => ApplyChangedBindings(changedProperty));"
        );
        emit_line!(output, 1, "}}");
        emit_line!(output, 0);
        emit_line!(
            output,
            1,
            "private void ApplyChangedBindings(string? changedProperty)"
        );
        emit_line!(output, 1, "{{");
        emit_line!(output, 2, "if (!_hasBindingContext) return;");
        for binding in document
            .bindings
            .iter()
            .filter(|binding| binding.mode == IrBindingMode::OneWay)
        {
            let source = &binding.source_path[0];
            emit_line!(
                output,
                2,
                "if (string.IsNullOrEmpty(changedProperty) || changedProperty == nameof({context_type}.{source}))"
            );
            emit_line!(output, 2, "{{");
            write_bound_setter(
                output,
                binding.target_node,
                &binding.target_property,
                source,
            )?;
            emit_line!(output, 2, "}}");
        }
        emit_line!(output, 1, "}}");
    }

    Ok(())
}

fn write_bound_setter(
    output: &mut String,
    node: usize,
    property: &str,
    source: &str,
) -> Result<(), String> {
    let setter = bound_setter(property)
        .ok_or_else(|| format!("binding property '{property}' has no C# runtime setter"))?;
    emit_line!(
        output,
        2,
        "_view.{setter}({node}, \"{}\", _bindingContext.{source});",
        escape_csharp_string(property)
    );
    Ok(())
}

fn bound_setter(property: &str) -> Option<&'static str> {
    match property {
        "Text" | "Content" => Some("SetBoundString"),
        _ => None,
    }
}

fn setter(property: &str) -> Option<(&'static str, &'static str)> {
    match property {
        "Text" => Some(("string?", "SetText")),
        "Content" => Some(("string?", "SetContent")),
        "Visibility" => Some(("Easydict.DirectXaml.Visibility", "SetVisibility")),
        "Foreground" => Some(("Easydict.DirectXaml.Color", "SetForeground")),
        "Background" => Some(("Easydict.DirectXaml.Color", "SetBackground")),
        "FontSize" => Some(("double", "SetFontSize")),
        "Opacity" => Some(("double", "SetOpacity")),
        _ => None,
    }
}

fn is_identifier(value: &str) -> bool {
    let mut chars = value.chars();
    matches!(chars.next(), Some('_') | Some('a'..='z') | Some('A'..='Z'))
        && chars.all(|ch| ch == '_' || ch.is_ascii_alphanumeric())
}

fn is_qualified_identifier(value: &str) -> bool {
    !value.is_empty() && value.split('.').all(is_identifier)
}

fn pascal_case(value: &str) -> String {
    let mut result = String::with_capacity(value.len());
    let mut uppercase = true;
    for ch in value.chars() {
        if !ch.is_ascii_alphanumeric() {
            uppercase = true;
        } else if uppercase {
            result.push(ch.to_ascii_uppercase());
            uppercase = false;
        } else {
            result.push(ch);
        }
    }
    result
}

fn escape_csharp_string(value: &str) -> String {
    value.replace('\\', "\\\\").replace('\"', "\\\"")
}

#[cfg(test)]
mod tests {
    use super::*;
    use dxaml_ir::{
        IrAction, IrBinding, IrBindingMode, IrDocument, IrMutableProperty, IrNamedSlot, IrNode,
        IrSource, IR_VERSION,
    };

    #[test]
    fn emits_typed_slot_and_action_accessors() {
        let document = IrDocument {
            ir_version: IR_VERSION.to_string(),
            compiler_version: "test".to_string(),
            source: IrSource {
                path: "Card.xaml".to_string(),
                hash: "fnv1a64:0000000000000000".to_string(),
            },
            class_name: "Easydict.Views.Card".to_string(),
            binding_context_type: None,
            features: Vec::new(),
            nodes: vec![IrNode {
                id: 0,
                kind: "textBlock".to_string(),
                parent: None,
                children: Vec::new(),
                text: None,
            }],
            properties: Vec::new(),
            named_slots: vec![IrNamedSlot {
                name: "ResultText".to_string(),
                node: 0,
                mutable: vec![
                    IrMutableProperty {
                        property: "Text".to_string(),
                        invalidation: vec!["measure".to_string(), "paint".to_string()],
                    },
                    IrMutableProperty {
                        property: "Content".to_string(),
                        invalidation: vec!["measure".to_string(), "paint".to_string()],
                    },
                ],
            }],
            bindings: Vec::new(),
            resources: Vec::new(),
            actions: vec![IrAction {
                node: 0,
                event: "pointerPressed".to_string(),
                handler: "OnPressed".to_string(),
            }],
            semantics: Vec::new(),
        };

        let source = generate(&document).expect("codegen");
        assert!(source.contains("namespace Easydict.Views;"));
        assert!(source.contains("class CardDirectBindings"));
        assert!(source.contains("SetResultTextText(string? value)"));
        assert!(source.contains("_view.SetText(\"ResultText\", value)"));
        assert!(source.contains("SetResultTextContent(string? value)"));
        assert!(source.contains("_view.SetContent(\"ResultText\", value)"));
        assert!(source.contains("Action0PointerPressed = \"OnPressed\""));
    }

    #[test]
    fn emits_one_time_and_one_way_bindings() {
        let document = IrDocument {
            ir_version: IR_VERSION.to_string(),
            compiler_version: "test".to_string(),
            source: IrSource {
                path: "Card.xaml".to_string(),
                hash: "fnv1a64:0000000000000000".to_string(),
            },
            class_name: "Easydict.Views.Card".to_string(),
            binding_context_type: Some("Easydict.Models.CardContext".to_string()),
            features: vec!["bindings".to_string()],
            nodes: vec![
                IrNode {
                    id: 0,
                    kind: "userControl".to_string(),
                    parent: None,
                    children: vec![1, 2],
                    text: None,
                },
                IrNode {
                    id: 1,
                    kind: "textBlock".to_string(),
                    parent: Some(0),
                    children: Vec::new(),
                    text: None,
                },
                IrNode {
                    id: 2,
                    kind: "button".to_string(),
                    parent: Some(0),
                    children: Vec::new(),
                    text: None,
                },
            ],
            properties: Vec::new(),
            named_slots: Vec::new(),
            bindings: vec![
                IrBinding {
                    target_node: 1,
                    target_property: "Text".to_string(),
                    source_path: vec!["ResultText".to_string()],
                    mode: IrBindingMode::OneTime,
                    invalidation: vec!["measure".to_string(), "paint".to_string()],
                },
                IrBinding {
                    target_node: 2,
                    target_property: "Content".to_string(),
                    source_path: vec!["Status".to_string()],
                    mode: IrBindingMode::OneWay,
                    invalidation: vec!["measure".to_string(), "paint".to_string()],
                },
            ],
            resources: Vec::new(),
            actions: Vec::new(),
            semantics: Vec::new(),
        };

        let source = generate(&document).expect("codegen");

        assert!(source
            .contains("private global::Easydict.Models.CardContext _bindingContext = default!;"));
        assert!(source.contains("_view.SetBoundString(1, \"Text\", _bindingContext.ResultText);"));
        assert!(source.contains("_view.SetBoundString(2, \"Content\", _bindingContext.Status);"));
        assert!(source.contains("newContext.PropertyChanged += OnBindingContextPropertyChanged;"));
        assert!(source
            .contains("changedProperty == nameof(global::Easydict.Models.CardContext.Status)"));
        assert!(!source
            .contains("changedProperty == nameof(global::Easydict.Models.CardContext.ResultText)"));
    }
}
